// Generated by LiveScript 1.2.0
angular.module('ui.choices', []).directive('choices', function($compile){
  return {
    restrict: 'E',
    replace: true,
    transclude: true,
    scope: {
      multiple: '=',
      ngModel: '=',
      id: '='
    },
    template: "<div class='btn-group' data-toggle='buttons' ng-transclude></div>",
    link: function(scope, element, attrs){
      return element.on('count-active', function(){
        var res$, i$, ref$, len$, e;
        res$ = [];
        for (i$ = 0, len$ = (ref$ = element.find('label.active')).length; i$ < len$; ++i$) {
          e = ref$[i$];
          res$.push($(e).attr('value'));
        }
        scope.ngModel = res$;
        return scope.$apply();
      });
    },
    controller: function($scope, $element){
      return this.isMultiple = function(){
        return $scope.multiple;
      };
    }
  };
}).directive('choice', function($compile){
  return {
    restrict: 'E',
    transclude: true,
    replace: true,
    require: "^choices",
    template: "<label class='btn btn-primary'><input type='radio'><span ng-transclude></span></label>",
    link: function(scope, element, attrs, ctrl){
      if (ctrl.isMultiple()) {
        element.find('input').attr('type', 'checkbox');
      }
      return element.on('click', function(){
        return setTimeout(function(){
          return element.parent().trigger('count-active');
        }, 0);
      });
    }
  };
});