// Generated by LiveScript 1.2.0
angular.module('ui.choices', []).directive('choices', function($compile){
  return {
    restrict: 'E',
    replace: true,
    transclude: true,
    scope: {
      model: '=ngModel',
      id: '='
    },
    template: "<div class='btn-group' data-toggle='buttons' ng-transclude></div>",
    link: function(scope, element, attrs){
      var update;
      scope.type = attrs.type;
      update = function(scope, element, target){
        var e, v, res$, i$, ref$, len$;
        if (element.find('label.active[alone]').length > 0) {
          if (!target) {
            target = element.find('label[alone]')[0];
          }
          if ($(target).attr('alone') !== undefined) {
            element.find('label').removeClass('active');
            $(target).addClass('active');
          } else {
            element.find('label[alone]').removeClass('active');
          }
        }
        if (scope.type === "array") {
          return scope.model = (function(){
            var i$, ref$, len$, results$ = [];
            for (i$ = 0, len$ = (ref$ = element.find('label.active')).length; i$ < len$; ++i$) {
              e = ref$[i$];
              results$.push($(e).attr('value'));
            }
            return results$;
          }());
        } else {
          if (typeof scope.model !== typeof {} || $.isArray(scope.model)) {
            scope.model = {};
          }
          res$ = [];
          for (i$ = 0, len$ = (ref$ = element.find('label')).length; i$ < len$; ++i$) {
            e = ref$[i$];
            res$.push([e.className, $(e).attr('value')]);
          }
          v = res$;
          v.filter(function(it){
            return it[0].search("active") >= 0;
          }).map(function(it){
            return (scope.model || (scope.model = {}))[it[1]] = true;
          });
          return v.filter(function(it){
            return it[0].search("active") < 0;
          }).map(function(it){
            return (scope.model || (scope.model = {}))[it[1]] = false;
          });
        }
      };
      update(scope, element);
      element.on('count-active', function(e, target){
        update(scope, element, target);
        return scope.$apply();
      });
      return scope.$watch('model', function(v){
        var res$, i$, len$, x, k, ref$, it, results$ = [];
        if (!v || (!v.length && scope.type === "array")) {
          return;
        }
        if (scope.type === "array") {
          res$ = [];
          for (i$ = 0, len$ = v.length; i$ < len$; ++i$) {
            x = v[i$];
            res$.push(x + "");
          }
          v = res$;
        } else {
          v = (function(){
            var results$ = [];
            for (k in v) {
              results$.push(k);
            }
            return results$;
          }()).filter(function(it){
            return v[it];
          });
        }
        for (i$ = 0, len$ = (ref$ = element.find('label')).length; i$ < len$; ++i$) {
          it = ref$[i$];
          it = $(it);
          if (in$(it.attr('value'), v)) {
            results$.push(it.addClass('active'));
          } else {
            results$.push(it.removeClass('active'));
          }
        }
        return results$;
      }, true);
    },
    controller: function($scope, $element){
      $scope.multiple = $element.attr('multiple');
      $scope.btnType = $element.attr('btn-type');
      this.isMultiple = function(){
        return $scope.multiple;
      };
      return this.btnType = function(){
        return $scope.btnType;
      };
    }
  };
}).directive('choice', function($compile){
  return {
    restrict: 'E',
    transclude: true,
    replace: true,
    require: "^choices",
    template: "<label class='btn'><input type='radio'><span ng-transclude></span></label>",
    link: function(scope, element, attrs, ctrl){
      var that;
      if ("active" in attrs) {
        element.addClass("active");
      }
      element.addClass((that = ctrl.btnType()) ? that : 'btn-primary');
      if (ctrl.isMultiple()) {
        element.find('input').attr('type', 'checkbox');
      }
      return element.on('click', function(){
        return setTimeout(function(){
          return element.parent().trigger('count-active', element);
        }, 0);
      });
    }
  };
});
function in$(x, xs){
  var i = -1, l = xs.length >>> 0;
  while (++i < l) if (x === xs[i]) return true;
  return false;
}